name: Deploy to Develop
on: 
  push:
    branches: [ develop ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: Adding keys
        run: |
          cd build
          echo -e "REACT_APP_USER_MAKERDAO_NETWORK_API=${{ secrets.STAGING_REACT_APP_USER_MAKERDAO_NETWORK_API }}\nREACT_APP_PASSWORD_MAKERDAO_NETWORK_API=${{ secrets.STAGING_REACT_APP_PASSWORD_MAKERDAO_NETWORK_API }}" >> .env
        shell: bash
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          source: "./build"
          target: "/var/www/staging"
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          overwrite: true
